### ISSUE TITLE
I noticed you named your repos 'pls help' what's the problem?

### ISSUE THREAD

**Issue by ghost** [CliveWearings/help#1]

**Comment by CliveWearings** [comment]
who is this

**Comment by ghost** [comment]
I'm the dude who put the template together.

**Comment by CliveWearings** [comment]
i didn't think anyone was going to view my changes when I named it that. i
just name things stupid things

**Comment by ghost** [comment]
I sometimes check via search if anyone has been using it, your repo names drew my attention.

**Comment by CliveWearings** [comment]
oh. i am having problems, but it's nothing i can't figure out and they
would be too difficult to explain over email
